In [75]:
"""
The Second-Order Moller-Plesset Perturbation Theory (MP2) Energy code
"""

import matplotlib.pyplot as plt
import numpy as np


nu_repul=np.loadtxt('enuc.dat')

overlap=np.loadtxt('s.dat')
over_mat=np.zeros((int(overlap[overlap.shape[0]-1,0]), int(overlap[overlap.shape[0]-1,0])))
for row in range(overlap.shape[0]):
    i1=int(overlap[row,0])
    i2=int(overlap[row,1])
    val=overlap[row,2]
    over_mat[i1-1,i2-1]=over_mat[i2-1,i1-1]=val
    
kinetic=np.loadtxt('t.dat')
kinetic_mat=np.zeros((kinetic[kinetic.shape[0]-1,0],kinetic[kinetic.shape[0]-1,0]))
for row in range(kinetic.shape[0]):
    i1=kinetic[row,0]
    i2=kinetic[row,1]
    val=kinetic[row,2]
    kinetic_mat[i1-1,i2-1]=kinetic_mat[i2-1,i1-1]=val
    
nuk_att=np.loadtxt('v.dat')
nuk_mat=np.zeros((nuk_att[nuk_att.shape[0]-1,0],nuk_att[nuk_att.shape[0]-1,0]))
for row in range(nuk_att.shape[0]):
    i1=nuk_att[row,0]
    i2=nuk_att[row,1]
    val=nuk_att[row,2]
    nuk_mat[i1-1,i2-1]=nuk_mat[i2-1,i1-1]=val
    


np.set_printoptions(precision=5)
print("Nuclear repulsion energy in Hartree \n",nu_repul,"\n")
print ("Overlap Integral Matrix \n \n", over_mat,"\n")
print ("Kinetic Energy Matrix \n \n", kinetic_mat,"\n")
print ("Nuclear Att. Integrals are  \n \n",nuk_mat,"\n")

H_core=kinetic_mat+nuk_mat
print ("This is the Core Hamiltonian Matrix \n \n",H_core,"\n")



Nuclear repulsion energy in Hartree 
 8.00236706181045 

Overlap Integral Matrix 
 
 [[ 1.       0.2367  -0.      -0.      -0.       0.03841  0.03841]
 [ 0.2367   1.       0.      -0.       0.       0.38614  0.38614]
 [-0.       0.       1.      -0.       0.       0.26844 -0.26844]
 [-0.      -0.      -0.       1.      -0.       0.20973  0.20973]
 [-0.       0.       0.      -0.       1.      -0.      -0.     ]
 [ 0.03841  0.38614  0.26844  0.20973 -0.       1.       0.18176]
 [ 0.03841  0.38614 -0.26844  0.20973 -0.       0.18176  1.     ]] 

Kinetic Energy Matrix 
 
 [[  2.90032e+01  -1.68011e-01   0.00000e+00   0.00000e+00  -0.00000e+00
   -8.41638e-03  -8.41638e-03]
 [ -1.68011e-01   8.08128e-01   0.00000e+00  -0.00000e+00   0.00000e+00
    7.05174e-02   7.05174e-02]
 [  0.00000e+00   0.00000e+00   2.52873e+00  -0.00000e+00   0.00000e+00
    1.47091e-01  -1.47091e-01]
 [  0.00000e+00  -0.00000e+00  -0.00000e+00   2.52873e+00  -0.00000e+00
    1.14920e-01   1.14920e-01]
 [ -0.00000e

/home/mintuser/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:20: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/home/mintuser/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:25: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/home/mintuser/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:28: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/home/mintuser/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:33: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
